language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_project: LoopKit.xcodeproj
xcode_scheme:
    - LoopKit
    - CarbKit
    - InsulinKit
    - GlucoseKit
# script:
#    - xcodebuild -project LoopKit.xcodeproj -scheme LoopKit -sdk iphonesimulator9.3 build test
